version: '3'

vars:
  PROJECT_NAME: SFDaaS
  SERVER_PORT:
    sh: echo "${SERVER_PORT:-8080}"
  M2_REPO: './.m2/sfdaas/repository'
  MVN_FLAGS: '-Dmaven.repo.local={{.M2_REPO}}'
  JAR_FILE: 'target/{{.PROJECT_NAME}}-jar-with-dependencies.jar'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all
    silent: true

  info:
    desc: Display project information
    cmds:
      - echo "Project{{":"}} {{.PROJECT_NAME}}"
      - echo "JAR File{{":"}} {{.JAR_FILE}}"
      - echo "App URL{{":"}} http{{":"}}//localhost{{":"}}{{.SERVER_PORT}}/{{.PROJECT_NAME}}"
      - echo "Data Path{{":"}} {{.USER_WORKING_DIR}}/data"
      - echo "M2 Repository{{":"}} {{.M2_REPO}}"
      - echo ""
      - echo "Java Version{{":"}}"
      - java -version
      - echo ""
      - echo "Maven Version{{":"}}"
      - mvn --version
    silent: true

  validate:
    desc: Validate project setup and dependencies
    cmds:
      - echo "Validating Java installation..."
      - java -version
      - echo "Validating Maven installation..."
      - mvn --version
      - echo "Validating data directory..."
      - test -d data && echo "✓ Data directory exists" || echo "✗ Data directory missing"
      - echo "Validating pom.xml..."
      - mvn {{.MVN_FLAGS}} validate
      - echo "✓ Project setup is valid"
    silent: true

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning build artifacts..."
      - mvn {{.MVN_FLAGS}} clean
      - echo "✓ Clean complete"
    silent: true

  expunge:
    desc: Complete cleanup - removes all build artifacts, dependencies, and metadata
    cmds:
      - echo "WARNING{{":"}} This will delete{{":"}}"
      - echo "  - Maven repository{{":"}} {{.M2_REPO}}"
      - echo "  - Build directory{{":"}} target/"
      - echo "  - Helper directory{{":"}} src-main/"
      - echo "  - Metadata{{":"}} .metadata/"
      - echo ""
      - echo "Expunging all build artifacts and dependencies..."
      - rm -rf {{.M2_REPO}}
      - rm -rf target/
      - rm -rf src-main/
      - rm -rf .metadata/
      - echo ""
      - echo "✓ Expunge complete!"
      - echo ""
      - echo "To rebuild from scratch{{":"}}"
      - echo "  task setup"
      - echo "  task build"
    silent: true

  compile:
    desc: Compile source code
    deps: [clean]
    cmds:
      - echo "Compiling source code..."
      - mvn {{.MVN_FLAGS}} compile
      - echo "✓ Compilation complete"
    silent: true

  test:
    desc: Run tests (if any)
    cmds:
      - echo "Running tests..."
      - mvn {{.MVN_FLAGS}} test
      - echo "✓ Tests complete"
    silent: true

  package:
    desc: Package application as standalone JAR
    deps: [clean]
    cmds:
      - echo "Building standalone JAR package..."
      - mvn {{.MVN_FLAGS}} package
      - echo "✓ Standalone JAR created at {{.JAR_FILE}}"
      - ls -lh {{.JAR_FILE}}
    silent: true

  build:
    desc: Full build (clean, compile, package)
    deps: [clean, compile]
    cmds:
      - task: package
    silent: true

  install:
    desc: Install to local Maven repository
    cmds:
      - echo "Installing to local Maven repository..."
      - mvn {{.MVN_FLAGS}} clean install
      - echo "✓ Installation complete"
    silent: true

  run:
    desc: Run application in background (standalone Netty server)
    deps:
      - stop
      - clean
      - setup
      - build
    cmds:
      - echo; echo "Starting Netty server in background on port {{.SERVER_PORT}}...";echo
      - nohup java -Dserver.port={{.SERVER_PORT}} -Dserver.contextPath=/{{.PROJECT_NAME}} -Dorekit.data.path=./data -jar {{.JAR_FILE}} > server.log 2>&1 &
      - echo $! > server.pid
      - sleep 3
      - echo "✓ Netty server started in background (PID{{":"}} $(cat server.pid))"
      - echo "Log file{{":"}} server.log";
      - echo "PID file{{":"}} server.pid"; echo
      - echo "Visit http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate/usage"; echo " or "
      - echo "Visit http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate?t0=2010-05-28T12:00:00.000&tf=2010-05-29T12:00:00.000&r0=[3198022.67,2901879.73,5142928.95]&v0=[-6129.640631,4489.647187,1284.511245]"
    silent: true

  stop:
    desc: Stop all background Netty servers
    cmds:
      - |
        set +e  # Don't exit on error
        echo "Stopping all SFDaaS server processes..."
        # Kill all SFDaaS JAR processes
        if pkill -f "{{.PROJECT_NAME}}-jar-with-dependencies.jar" 2>/dev/null; then
          echo "✓ SFDaaS server processes killed"
        else
          echo "No SFDaaS server processes found"
        fi
        # Also kill any process on the port as fallback
        PORT_PID=$(lsof -ti:{{.SERVER_PORT}} 2>/dev/null)
        if [ -n "$PORT_PID" ]; then
          if kill -9 $PORT_PID 2>/dev/null; then
            echo "✓ Killed process on port {{.SERVER_PORT}}"
          fi
        fi
        # Clean up PID and log files
        rm -f server.pid server.log tomcat.pid tomcat.log
        echo "✓ All SFDaaS servers stopped"
        exit 0
    silent: true

  ps:
    desc: Show all running SFDaaS server processes
    cmds:
      - |
        echo "Checking for SFDaaS server processes..."
        SERVER_PROCS=$(ps aux | grep -i "{{.PROJECT_NAME}}-jar-with-dependencies.jar" | grep -v grep || true)
        if [ -n "$SERVER_PROCS" ]; then
          echo "Running SFDaaS server processes{{":"}}"
          echo "$SERVER_PROCS" | awk '{print "  PID: " $2 " | Started: " $9 " | Memory: " $4 "%"}'
          echo ""
          echo "Total: $(echo "$SERVER_PROCS" | wc -l | tr -d ' ') process(es)"
        else
          echo "✓ No SFDaaS server processes running"
        fi
        echo ""
        PORT_PID=$(lsof -ti:{{.SERVER_PORT}} 2>/dev/null || true)
        if [ -n "$PORT_PID" ]; then
          echo "Process on port {{.SERVER_PORT}}: PID $PORT_PID"
        else
          echo "✓ Port {{.SERVER_PORT}} is free"
        fi
        exit 0
    silent: true

  deps:
    desc: Display dependency tree
    cmds:
      - echo "Dependency tree{{":"}}"
      - mvn {{.MVN_FLAGS}} dependency:tree

  deps-analyze:
    desc: Analyze dependencies for issues
    cmds:
      - echo "Analyzing dependencies..."
      - mvn {{.MVN_FLAGS}} dependency:analyze
    silent: true

  deps-update:
    desc: Check for dependency updates
    cmds:
      - echo "Checking for dependency updates..."
      - mvn {{.MVN_FLAGS}} versions:display-dependency-updates
    silent: true

  deps-location:
    desc: Show where dependencies are stored in M2 repository
    cmds:
      - echo "Maven Local Repository{{":"}} {{.M2_REPO}}"
      - echo ""
      - echo "Project Dependencies Location{{":"}}"
      - echo "  OreKit{{":"}} {{.M2_REPO}}/org/orekit/orekit/13.1.2/"
      - echo "  Hipparchus Core{{":"}} {{.M2_REPO}}/org/hipparchus/hipparchus-core/4.0.2/"
      - echo "  Spymemcached{{":"}} {{.M2_REPO}}/net/spy/spymemcached/2.12.3/"
      - echo ""
      - echo "Checking if dependencies exist{{":"}}"
      - test -d {{.M2_REPO}}/org/orekit/orekit/13.1.2 && echo "  ✓ OreKit 13.1.2" || echo "  ✗ OreKit 13.1.2 not found"
      - test -d {{.M2_REPO}}/org/hipparchus/hipparchus-core/4.0.2 && echo "  ✓ Hipparchus 4.0.2" || echo "  ✗ Hipparchus 4.0.2 not found"
      - test -d {{.M2_REPO}}/net/spy/spymemcached/2.12.3 && echo "  ✓ Spymemcached 2.12.3" || echo "  ✗ Spymemcached 2.12.3 not found"
      - echo ""
      - echo "Repository size{{":"}}"
      - du -sh {{.M2_REPO}} 2>/dev/null || echo "  Unable to calculate size"
    silent: true

  verify:
    desc: Verify the built JAR file
    cmds:
      - |
        if [ ! -f {{.JAR_FILE}} ]; then
          echo "Error: JAR file not found. Run 'task build' first."
          exit 1
        fi
        echo "JAR file information:"
        ls -lh {{.JAR_FILE}}
        echo ""
        echo "JAR file contents (first 20 entries):"
        jar tf {{.JAR_FILE}} | head -20
        echo "..."
        echo ""
        echo "✓ JAR file is valid"
    silent: true

  open:
    desc: Open usage documentation in browser
    cmds:
      - |
        if command -v open > /dev/null; then
          open http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate/usage
        elif command -v xdg-open > /dev/null; then
          xdg-open http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate/usage
        else
          echo "Please open http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate/usage in your browser"
        fi
    silent: true

  usage:
    desc: Show usage documentation URL
    cmds:
      - echo;echo "Please open http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate/usage in your browser"; echo
    silent: true

  logs:
    desc: Tail the server log file
    cmds:
      - |
        if [ -f server.log ]; then
          tail -f server.log
        else
          echo "No log file found. Is the server running?"
        fi
    silent: true

  setup:
    desc: Initial project setup and validation
    cmds:
      - echo "Setting up {{.PROJECT_NAME}} project..."
      - task: validate
      - echo ""
      - echo "Creating necessary directories..."
      - mkdir -p target
      - mkdir -p src-main
      - echo ""
      - echo "Downloading dependencies..."
      - mvn {{.MVN_FLAGS}} dependency:resolve
      - echo ""
      - echo "✓ Setup complete!"
      - echo ""
      - echo "Next steps{{":"}}"
      - echo "  1. Run 'task run' to setup, build and start the server"
      - echo "  2. Visit http://localhost:{{.SERVER_PORT}}/{{.PROJECT_NAME}}/orekit/propagate/usage"
    silent: true

  release:
    desc: Create a release build with documentation
    cmds:
      - echo "Creating release build..."
      - task: clean
      - task: build
      - task: verify
      - echo ""
      - echo "Generating documentation..."
      - mvn {{.MVN_FLAGS}} javadoc:javadoc || echo "Javadoc generation skipped"
      - echo ""
      - echo "✓ Release build complete!"
      - echo ""
      - echo "Artifacts{{":"}}"
      - ls -lh {{.JAR_FILE}}
    silent: true

  status:
    desc: Check application status
    cmds:
      - |
        echo "Application Status:"
        echo "===================="
        echo ""
        if [ -f server.pid ]; then
          PID=$(cat server.pid)
          if ps -p $PID > /dev/null 2>&1; then
            echo "Status: RUNNING (PID: $PID)"
          else
            echo "Status: STOPPED (stale PID file)"
          fi
        else
          echo "Status: STOPPED"
        fi
        echo ""
        echo "Checking port {{.SERVER_PORT}}..."
        if lsof -Pi :{{.SERVER_PORT}} -sTCP:LISTEN -t >/dev/null 2>&1 || netstat -an 2>/dev/null | grep {{.SERVER_PORT}} | grep LISTEN >/dev/null 2>&1; then
          echo "Port {{.SERVER_PORT}}: IN USE"
        else
          echo "Port {{.SERVER_PORT}}: AVAILABLE"
        fi
        echo ""
        if [ -f {{.JAR_FILE}} ]; then
          echo "JAR file: EXISTS"
        else
          echo "JAR file: NOT FOUND"
        fi
    silent: true

  help:
    desc: Show detailed help for common tasks
    cmds:
      - |
        cat << 'EOF'
        Space Flight Dynamics as a Service (SFDaaS) - Task Runner Help
        ================================================================

        Quick Start:
        ------------
        1. task setup       # Initial setup and validation
        2. task build       # Build the application
        3. task run         # Run with embedded Tomcat

        Common Tasks:
        -------------
        task build          # Clean build and package
        task run            # Run with embedded Tomcat
        task stop           # Stop server
        task status         # Check if server is running

        Build Tasks:
        ------------
        task clean          # Remove build artifacts
        task compile        # Compile source code only
        task package        # Create WAR file
        task verify         # Verify the built WAR

        Deployment:
        -----------
        task deploy-tomcat  # Deploy to external Tomcat
        task undeploy-tomcat # Remove from external Tomcat

        Development:
        ------------
        task quick-test     # Quick build and test
        task full-cycle     # Complete development cycle

        Information:
        ------------
        task info           # Show project information
        task deps           # Show dependency tree
        task logs           # Tail server logs
        task usage          # Open usage docs in browser

        For more tasks, run: task --list-all

        Configuration:
        --------------
        CATALINA_HOME: Set this for external Tomcat deployment
        TOMCAT_PORT: Default 8080, override with TOMCAT_PORT=8081 task run

        Examples:
        ---------
        task build                              # Build the project
        task run                                # Start server
        CATALINA_HOME=/opt/tomcat task deploy-tomcat  # Deploy to Tomcat

        EOF
    silent: true
